# Используем легкий Node.js образ
FROM node:20-alpine

# Рабочая директория
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь фронтенд-код
COPY . .

# Указываем порт для Next.js
EXPOSE 3000

# Команда запуска
CMD ["npm", "run", "dev"]
